{% set name = "epix-hr-single-10k" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: 64812960625af29874583e41ffc477b70afeef5ec12b0f46157425c15e907e7c

build:
  skip: True  # [win or osx]
  noarch: python
  number: 6
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/cameralink-gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cameralink-gateway software and firmware'
  description: |
    firmware for cameralink-gateway devices.
  doc_url: https://github.com/slaclab/cameralink-gateway
  dev_url: https://github.com/slaclab/cameralink-gateway

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

